spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cards_domain
        username: cards_domain
        password: changeme
        driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        maximum-pool-size: 5
        auto-commit: false
        connection-timeout: 1000
        idle-timeout: 60000
        max-lifetime: 180000

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
    version: '@springdoc.version@'