server:
    port: 10000
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param
        include-exception: false

spring:
    application:
      name: cards-info
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cards_domain
        username: cards_domain
        password: changeme
        driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


springdoc:
    version: '@springdoc.version@'