version: '3'
services:
  mysql-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=changeme"
    volumes:
#      - $PWD/volumes/mysql:/var/lib/mysql
      - $PWD/volumes/mysql-init:/docker-entrypoint-initdb.d