server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native

#  config:
#    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true